spring:
  profiles:
    active:
    - dev

---

spring:
  profiles: dev   #开发环境
  application:
    name: microservicecloud-config-demo01-dev

---

spring:
  profiles: test  #测试环境
  application:
    name: microservicecloud-config-demo01-test

#注意：请保存UTF-8格式 ！！！

