server:
  port: 7001
  
eureka:
  server:
    enable-self-preservation: false # 禁止自我保护模式
  instance:
    #hostname: localhost  #Eureka服务端的实例名称
     hostname: eureka7001.com #这里需要把 C:\Windows\System32\drivers\etc 里 hosts 文件复制出来再修改文件：加上 127.0.0.1  eureka7001.com、 127.0.0.1 eureka7002.com、 127.0.0.1 eureka7003.com这三个映射
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己
    fetch-registry: false   # false 表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server交互的地址查询服务和组成服务
       defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    